-- Why: Numeric surrogate keys keep joins and procedure parameters simple for a small Oracle project.

CREATE SEQUENCE seq_categories START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_products START WITH 1001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_orders START WITH 20260001 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_order_items START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_stock_history START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE seq_error_log START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
