WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM dba_users
     WHERE username = 'APP_USER';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[CREATE USER app_user IDENTIFIED BY "AppUser1234!"]';
    END IF;
END;
/

GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE,
      CREATE PROCEDURE, CREATE TRIGGER, CREATE TYPE TO app_user;

ALTER USER app_user QUOTA UNLIMITED ON USERS;
