WHENEVER OSERROR EXIT FAILURE ROLLBACK;
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

SET DEFINE OFF;
SET SERVEROUTPUT ON;
SET ECHO ON;

ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = APP_USER;

PROMPT Bootstrap completed successfully.
EXIT SUCCESS;
